name: Generate File List
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Позволяет запускать вручную

permissions:
  contents: write

jobs:
  generate-file-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate File List
        uses: nick2bad4u/generate-repo-file-list@v1
        with:
          directory: "."
          output-format: "markdown" # или "html"
          output-file: "FILE_LIST.md" # Файл, в который сохранится структура
          respect-gitignore: "true"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update file list automatically"
